MATERIAL_ICON_LISTS = ['subtitles', 'volume_off', 'restore', 'restore_page', 'room', 'rounded_corner', 'rowing',
                       'schedule', 'sms', 'sim_card_alert', 'sd_card', 'settings_input_antenna',
                       'settings_input_component', 'settings_input_composite', 'settings_input_hdmi',
                       'settings_input_svideo', 'settings_ethernet', 'local_mall', 'perm_identity',
                       'local_library', 'local_laundry_service', 'local_bar', 'local_cafe', 'local_car_wash',
                       'local_convenience_store', 'local_dining', 'perm_contact_calendar', 'motorcycle',
                       'do_not_disturb', 'disc_full', 'confirmation_number', 'school', 'sentiment_dissatisfied',
                       'sentiment_neutral', 'sentiment_satisfied', 'sentiment_very_dissatisfied',
                       'sentiment_very_satisfied', 'share', 'camera_rear', 'camera_roll', 'center_focus_strong',
                       'whatshot', 'chat_bubble', 'chat', 'person_add', 'person_outline', 'plus_one', 'poll', 'public',
                       'airport_shuttle', 'ac_unit', 'wifi', 'wc', 'vpn_lock', 'airline_seat_legroom_normal',
                       'airline_seat_legroom_reduced', 'airline_seat_recline_extra', 'polymer', 'child_friendly',
                       'child_care', 'casino', 'business_center', 'beach_access', 'subscriptions',
                       'stop', 'sort_by_alpha', 'snooze', 'slow_motion_video', 'skip_previous', 'skip_next',
                       'line_weight', 'list', 'lock', 'lock_open', 'lock_outline', 'loyalty', 'markunread_mailbox',
                       'all_inclusive', 'domain', 'cake', 'spa', 'smoking_rooms', 'smoke_free', 'search', 'sms_failed',
                       'sync', 'sync_disabled', 'sync_problem', 'contacts', 'dialer_sip', 'notifications',
                       'payment', 'pan_tool', 'pageview', 'open_with', 'open_in_new', 'local_hotel', 'settings_cell',
                       'surround_sound', 'video_call', 'check_box', 'invert_colors', 'label', 'label_outline',
                       'language', 'launch', 'lightbulb_outline', 'line_style', 'contact_phone', 'call_split',
                       'call_received', 'local_drink', 'call', 'business', 'web_asset', 'web', 'volume_up',
                       'record_voice_over', 'report_problem', 'reorder', 'remove_shopping_cart', 'redeem',
                       'center_focus_weak', 'collections', 'collections_bookmark', 'color_lens', 'perm_camera_mic',
                       'dialpad', 'email', 'forum', 'import_contacts', 'videocam', 'videocam_off', 'volume_down',
                       'volume_mute', 'rv_hookup', 'system_update', 'do_not_disturb_alt', 'video_library',
                       'room_service', 'pool', 'kitchen', 'hot_tub', 'mail_outline', 'message', 'no_sim',
                       'notifications_active', 'notifications_none', 'notifications_off', 'phone', 'local_atm',
                       'tap_and_play', 'time_to_leave', 'chat_bubble_outline', 'clear_all', 'comment', 'contact_mail',
                       'play_for_work', 'golf_course', 'free_breakfast', 'fitness_center', 'video_label',
                       'settings_applications', 'settings_backup_restore', 'settings_bluetooth', 'settings_brightness',
                       'note_add', 'offline_pin', 'opacity', 'open_in_browser', 'settings', 'vibration', 'voice_chat',
                       'shop_two', 'shop', 'bluetooth_audio', 'airline_seat_recline_normal', 'layers_clear',
                       'local_movies', 'local_offer', 'shopping_basket', 'radio_button_checked',
                       'local_parking', 'star_half', 'star_border', 'star', 'radio_button_unchecked',
                       'indeterminate_check_box', 'settings_voice', 'perm_data_setting', 'perm_device_information',
                       'perm_media', 'perm_phone_msg', 'perm_scan_wifi', 'pets', 'picture_in_picture',
                       'picture_in_picture_alt', 'settings_remote', 'settings_power', 'personal_video',
                       'import_export', 'invert_colors_off', 'live_help', 'location_off', 'location_on',
                       'settings_phone', 'settings_overscan', 'phone_forwarded', 'phone_bluetooth_speaker',
                       'ondemand_video', 'no_encryption', 'power', 'phone_paused', 'phone_missed', 'phone_locked',
                       'phone_in_talk', 'camera_front', 'camera_alt', 'person', 'people_outline',
                       'local_airport', 'event_available', 'event_busy', 'event_note', 'folder_special', 'live_tv',
                       'camera', 'local_grocery_store', 'local_gas_station', 'local_florist', 'call_missed_outgoing',
                       'call_missed', 'priority_high', 'query_builder', 'do_not_disturb_on',
                       'call_merge', 'call_made', 'call_end', 'mood_bad', 'mood', 'location_city', 'group_add', 'group',
                       'local_hospital', 'compare', 'colorize', 'hotel', 'layers', 'pregnant_woman', 'print',
                       'question_answer', 'receipt', 'power_settings_new', 'enhanced_encryption', 'drive_eta',
                       'do_not_disturb_off', 'network_locked', 'network_check', 'more', 'mms', 'local_activity',
                       'people', 'party_mode', 'pages', 'notifications_paused', 'check_box_outline_blank']
